name: live_streaming
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ">=5.5.3+2 <5.6.1"
  zego_uikit_prebuilt_live_streaming: ^2.18.1

dev_dependencies:
  dart_code_metrics: any

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
